miasta_wojewodztwa = {
    'Aleksandrów Łódzki': 'łódzkie',
    'Bełżyce': 'lubelskie',
    'Białogard': 'zachodniopomorskie',
    'Bielawa': 'dolnośląskie',
    'Bielsko-Biała': 'śląskie',
    'Błonie': 'mazowieckie',
    'Bochnia': 'małopolskie',
    'Bolesławiec': 'dolnośląskie',
    'Braniewo': 'warmińsko-mazurskie',
    'Brodnica': 'kujawsko-pomorskie',
    'Brzeg Dolny': 'dolnośląskie',
    'Brzeg': 'opolskie',
    'Brzesko': 'małopolskie',
    'Brzeszcze': 'małopolskie',
    'Brzeziny': 'łódzkie',
    'Bukowno': 'małopolskie',
    'Bystrzyca Kłodzka': 'dolnośląskie',
    'Bytom': 'śląskie',
    'Chodzież': 'wielkopolskie',
    'Chojna': 'zachodniopomorskie',
    'Choszczno': 'zachodniopomorskie',
    'Chybie': 'śląskie',
    'Ciechocinek': 'kujawsko-pomorskie',
    'Cieszyn': 'śląskie',
    'Czarnków': 'wielkopolskie',
    'Czerwionka-Leszczyny': 'śląskie',
    'Dąbrowa Górnicza': 'śląskie',
    'Darłowo': 'zachodniopomorskie',
    'Dęblin': 'mazowieckie',
    'Dębno': 'zachodniopomorskie',
    'Drawsko Pomorskie': 'zachodniopomorskie',
    'Drezdenko': 'lubuskie',
    'Działdowo': 'warmińsko-mazurskie',
    'Dzierżoniów': 'dolnośląskie',
    'Ełk': 'warmińsko-mazurskie',
    'Gdańsk': 'pomorskie',
    'Gdynia': 'pomorskie',
    'Giżycko': 'warmińsko-mazurskie',
    'Głogów': 'dolnośląskie',
    'Głubczyce': 'opolskie',
    'Głuchołazy': 'opolskie',
    'Gniezno': 'wielkopolskie',
    'Goleniów': 'zachodniopomorskie',
    'Golub-Dobrzyń': 'kujawsko-pomorskie',
    'Góra': 'dolnośląskie',
    'Gorzów Wielkopolski': 'lubuskie',
    'Gostyń': 'wielkopolskie',
    'Grajewo': 'mazowieckie',
    'Grodzisk Wielkopolski': 'wielkopolskie',
    'Grójec': 'mazowieckie',
    'Grudziądz': 'kujawsko-pomorskie',
    'Gryfice': 'zachodniopomorskie',
    'Gryfino': 'zachodniopomorskie',
    'Iława': 'warmińsko-mazurskie',
    'Jarocin': 'wielkopolskie',
    'Jawor': 'dolnośląskie',
    'Jelcz-Laskowice': 'dolnośląskie',
    'Jelcz': 'dolnośląskie',
    'Jelenia Góra': 'dolnośląskie',
    'Kamienna Góra': 'dolnośląskie',
    'Katowice': 'śląskie',
    'Kępno': 'wielkopolskie',
    'Kluczbork': 'opolskie',
    'Kolbuszowa': 'podkarpackie',
    'Kołobrzeg': 'zachodniopomorskie',
    'Konin': 'wielkopolskie',
    'Kostrzyn nad Odrą': 'lubuskie',
    'Krotoszyn': 'wielkopolskie',
    'Krynica-Zdrój': 'małopolskie',
    'Kwidzyn': 'pomorskie',
    'Lębork': 'pomorskie',
    'Legnica': 'dolnośląskie',
    'Leszno': 'wielkopolskie',
    'Libiąż': 'małopolskie',
    'Lipno': 'kujawsko-pomorskie',
    'Łowicz': 'łódzkie',
    'Lubań': 'dolnośląskie',
    'Luboń': 'wielkopolskie',
    'Lubsko': 'lubuskie',
    'Lwówek Śląski': 'dolnośląskie',
    'Malbork': 'pomorskie',
    'Miechów': 'małopolskie',
    'Międzychód': 'wielkopolskie',
    'Międzyrzecz': 'lubuskie',
    'Milicz': 'dolnośląskie',
    'Mława': 'mazowieckie',
    'Mogilno': 'kujawsko-pomorskie',
    'Myślibórz': 'zachodniopomorskie',
    'Namysłów': 'opolskie',
    'Nowa Ruda': 'dolnośląskie',
    'Nowa Sól': 'lubuskie',
    'Nowogard': 'zachodniopomorskie',
    'Nowy Tomyśl': 'wielkopolskie',
    'Oborniki Śląskie': 'dolnośląskie',
    'Oborniki': 'wielkopolskie',
    'Oława': 'dolnośląskie',
    'Oleśnica': 'dolnośląskie',
    'Olsztyn': 'warmińsko-mazurskie',
    'Opalenica': 'wielkopolskie',
    'Ostróda': 'warmińsko-mazurskie',
    'Ostrów Wielkopolski': 'wielkopolskie',
    'Ostrzeszów': 'wielkopolskie',
    'Ozorków': 'łódzkie',
    'Pabianice': 'łódzkie',
    'Pajęczno': 'łódzkie',
    'Piekary Śląskie': 'śląskie',
    'Piła': 'wielkopolskie',
    'Polanica-Zdrój': 'dolnośląskie',
    'Police': 'zachodniopomorskie',
    'Polkowice': 'dolnośląskie',
    'Poznań': 'wielkopolskie',
    'Przemków': 'dolnośląskie',
    'Przeworsk': 'podkarpackie',
    'Pszczyna': 'śląskie',
    'Puck': 'pomorskie',
    'Pułtusk': 'mazowieckie',
    'Radlin': 'śląskie',
    'Radomsko': 'łódzkie',
    'Radzymin': 'mazowieckie',
    'Rawa Mazowiecka': 'łódzkie',
    'Rawicz': 'wielkopolskie',
    'Ruda Śląska': 'śląskie',
    'Ryki': 'lubelskie',
    'Rzeszów': 'podkarpackie',
    'Sanok': 'podkarpackie',
    'Skierniewice': 'łódzkie',
    'Skwierzyna': 'lubuskie',
    'Sławno': 'zachodniopomorskie',
    'Słubice': 'lubuskie',
    'Słupca': 'wielkopolskie',
    'Śrem': 'wielkopolskie',
    'Środa Śląska': 'dolnośląskie',
    'Środa Wielkopolska': 'wielkopolskie',
    'Stalowa Wola': 'podkarpackie',
    'Stare Miasto': 'kujawsko-pomorskie',
    'Starogard Gdański': 'pomorskie',
    'Strzelce Krajeńskie': 'lubuskie',
    'Strzelce Opolskie': 'opolskie',
    'Sucha Beskidzka': 'małopolskie',
    'Sulechów': 'lubuskie',
    'Sulęcin': 'lubuskie',
    'Swarzędz': 'wielkopolskie',
    'Świdnica': 'dolnośląskie',
    'Świdwin': 'zachodniopomorskie',
    'Świebodzice': 'dolnośląskie',
    'Świebodzin': 'lubuskie',
    'Szczecin': 'zachodniopomorskie',
    'Szczecinek': 'zachodniopomorskie',
    'Szczytno': 'warmińsko-mazurskie',
    'Szprotawa': 'lubuskie',
    'Tczew': 'pomorskie',
    'Tomaszów Lubelski': 'lubelskie',
    'Toruń': 'kujawsko-pomorskie',
    'Trzebiatów': 'zachodniopomorskie',
    'Trzebinia': 'małopolskie',
    'Trzebnica': 'dolnośląskie',
    'Turek': 'wielkopolskie',
    'Wągrowiec': 'wielkopolskie',
    'Wałcz': 'zachodniopomorskie',
    'Wejherowo': 'pomorskie',
    'Wieliczka': 'małopolskie',
    'Wieluń': 'łódzkie',
    'Wieruszów': 'łódzkie',
    'Wołów': 'dolnośląskie',
    'Wolsztyn': 'wielkopolskie',
    'Września': 'wielkopolskie',
    'Wschowa': 'lubuskie',
    'Zamość': 'lubelskie',
    'Żary': 'lubuskie',
    'Zbąszyń': 'wielkopolskie',
    'Zduńska Wola': 'łódzkie',
    'Zielona Góra': 'lubuskie',
    'Złocieniec': 'zachodniopomorskie'
}
wojewodztwa_lokalizacje = {
    'dolnośląskie': {'lat': 51.1079, 'lon': 17.0385},  # Wrocław
    'kujawsko-pomorskie': {'lat': 53.1235, 'lon': 18.0076},  # Bydgoszcz
    'lubelskie': {'lat': 51.2465, 'lon': 22.5684},  # Lublin
    'lubuskie': {'lat': 52.7394, 'lon': 15.2370},  # Zielona Góra
    'łódzkie': {'lat': 51.7592, 'lon': 19.4560},  # Łódź
    'małopolskie': {'lat': 50.0647, 'lon': 19.9450},  # Kraków
    'mazowieckie': {'lat': 52.2297, 'lon': 21.0122},  # Warszawa
    'opolskie': {'lat': 50.6751, 'lon': 17.9213},  # Opole
    'podkarpackie': {'lat': 50.0413, 'lon': 21.9990},  # Rzeszów
    'podlaskie': {'lat': 53.1325, 'lon': 23.1688},  # Białystok
    'pomorskie': {'lat': 54.3520, 'lon': 18.6466},  # Gdańsk
    'śląskie': {'lat': 50.2649, 'lon': 19.0238},  # Katowice
    'świętokrzyskie': {'lat': 50.8661, 'lon': 20.6286},  # Kielce
    'warmińsko-mazurskie': {'lat': 53.7799, 'lon': 20.4942},  # Olsztyn
    'wielkopolskie': {'lat': 52.4064, 'lon': 16.9252},  # Poznań
    'zachodniopomorskie': {'lat': 53.4285, 'lon': 14.5528}  # Szczecin
}