miasta_wojewodztwa = {
    "Aleksandrów Łódzki": "Łódzkie",
    "Bełżyce": "Lubelskie",
    "Białogard": "Zachodniopomorskie",
    "Bielawa": "Dolnośląskie",
    "Biała": "Opolskie",
    "Błonie": "Mazowieckie",
    "Bochnia": "Małopolskie",
    "Braniewo": "Warmińsko-Mazurskie",
    "Brodnica": "Kujawsko-Pomorskie",
    "Brzeg": "Opolskie",
    "Brzesko": "Małopolskie",
    "Brzeszcze": "Małopolskie",
    "Brzeziny": "Łódzkie",
    "Bukowno": "Małopolskie",
    "Bystrzyca Kłodzka": "Dolnośląskie",
    "Bytom": "Śląskie",
    "Chodzież": "Wielkopolskie",
    "Chojna": "Zachodniopomorskie",
    "Choszczno": "Zachodniopomorskie",
    "Chybie": "Śląskie",
    "Ciechocinek": "Kujawsko-Pomorskie",
    "Cieszyn": "Śląskie",
    "Czarnków": "Wielkopolskie",
    "Dąbrowa Górnicza": "Śląskie",
    "Darłowo": "Zachodniopomorskie",
    "Dęblin": "Lubelskie",
    "Dębno": "Zachodniopomorskie",
    "Drawsko Pomorskie": "Zachodniopomorskie",
    "Drezdenko": "Lubuskie",
    "Działdowo": "Warmińsko-Mazurskie",
    "Dzierżoniów": "Dolnośląskie",
    "Ełk": "Warmińsko-Mazurskie",
    "Giżycko": "Warmińsko-Mazurskie",
    "Głogów": "Dolnośląskie",
    "Głubczyce": "Opolskie",
    "Gniezno": "Wielkopolskie",
    "Goleniów": "Zachodniopomorskie",
    "Góra": "Dolnośląskie",
    "Gorzów Wielkopolski": "Lubuskie",
    "Grajewo": "Podlaskie",
    "Grójec": "Mazowieckie",
    "Grudziądz": "Kujawsko-Pomorskie",
    "Gryfice": "Zachodniopomorskie",
    "Gryfino": "Zachodniopomorskie",
    "Iława": "Warmińsko-Mazurskie",
    "Jarocin": "Wielkopolskie",
    "Jawor": "Dolnośląskie",
    "Jelcz Laskowice": "Dolnośląskie",
    "Jelenia Góra": "Dolnośląskie",
    "Kamienna Góra": "Dolnośląskie",
    "Katowice": "Śląskie",
    "Kępno": "Wielkopolskie",
    "Kluczbork": "Opolskie",
    "Kolbuszowa": "Podkarpackie",
    "Kołobrzeg": "Zachodniopomorskie",
    "Konin": "Wielkopolskie",
    "Krotoszyn": "Wielkopolskie",
    "Krynica Zdrój": "Małopolskie",
    "Kwidzyn": "Pomorskie",
    "Lębork": "Pomorskie",
    "Legnica": "Dolnośląskie",
    "Libiąż": "Małopolskie",
    "Lipno": "Kujawsko-Pomorskie",
    "Łowicz": "Łódzkie",
    "Lubań": "Dolnośląskie",
    "Luboń": "Wielkopolskie",
    "Lubsko": "Lubuskie",
    "Lwówek Śląski": "Dolnośląskie",
    "Malbork": "Pomorskie",
    "Międzychód": "Wielkopolskie",
    "Milicz": "Dolnośląskie",
    "Mława": "Mazowieckie",
    "Mogilno": "Kujawsko-Pomorskie",
    "Myślibórz": "Zachodniopomorskie",
    "Namysłów": "Opolskie",
    "Nowa Ruda": "Dolnośląskie",
    "Nowa Sól": "Lubuskie",
    "Nowogard": "Zachodniopomorskie",
    "Nowy Tomyśl": "Wielkopolskie",
    "Oborniki Śląskie": "Dolnośląskie",
    "Oborniki": "Wielkopolskie",
    "Oława": "Dolnośląskie",
    "Oleśnica": "Dolnośląskie",
    "Olsztyn": "Warmińsko-Mazurskie",
    "Opalenica": "Wielkopolskie",
    "Ostróda": "Warmińsko-Mazurskie",
    "Ostrów Wielkopolski": "Wielkopolskie",
    "Ostrzeszów": "Wielkopolskie",
    "Ozorków": "Łódzkie",
    "Pajęczno": "Łódzkie",
    "Piekary Śląskie": "Śląskie",
    "Piła": "Wielkopolskie",
    "Polanica Zdrój": "Dolnośląskie",
    "Polkowice": "Dolnośląskie",
    "Poznań": "Wielkopolskie",
    "Przemków": "Dolnośląskie",
    "Przeworsk": "Podkarpackie",
    "Pszczyna": "Śląskie",
    "Pułtusk": "Mazowieckie",
    "Radlin": "Śląskie",
    "Radomsko": "Łódzkie",
    "Radzymin": "Mazowieckie",
    "Rawa Mazowiecka": "Łódzkie",
    "Rawicz": "Wielkopolskie",
    "Ruda Śląska": "Śląskie",
    "Ryki": "Lubelskie",
    "Rzeszów": "Podkarpackie",
    "Skierniewice": "Łódzkie",
    "Skwierzyna": "Lubuskie",
    "Sławno": "Zachodniopomorskie",
    "Słubice": "Lubuskie",
    "Słupca": "Wielkopolskie",
    "Śrem": "Wielkopolskie",
    "Środa Śląska": "Dolnośląskie",
    "Środa Wielkopolska": "Wielkopolskie",
    "Stalowa Wola": "Podkarpackie",
    "Stare Miasto": "Wielkopolskie",
    "Starogard Gdański": "Pomorskie",
    "Strzelce Krajeńskie": "Lubuskie",
    "Strzelce Opolskie": "Opolskie",
    "Sucha Beskidzka": "Małopolskie",
    "Sulechów": "Lubuskie",
    "Sulęcin": "Lubuskie",
    "Świdnica": "Dolnośląskie",
    "Świdwin": "Zachodniopomorskie",
    "Świebodzice": "Dolnośląskie",
    "Szczecin": "Zachodniopomorskie",
    "Szczecinek": "Zachodniopomorskie",
    "Szczytno": "Warmińsko-Mazurskie",
    "Szprotawa": "Lubuskie",
    "Tczew": "Pomorskie",
    "Tomaszów Lubelski": "Lubelskie",
    "Toruń": "Kujawsko-Pomorskie",
    "Trzebiatów": "Zachodniopomorskie",
    "Trzebnica": "Dolnośląskie",
    "Turek": "Wielkopolskie",
    "Wągrowiec": "Wielkopolskie",
    "Wejherowo": "Pomorskie",
    "Wieliczka": "Małopolskie",
    "Wieluń": "Łódzkie",
    "Wieruszów": "Łódzkie",
    "Wołów": "Dolnośląskie",
    "Wolsztyn": "Wielkopolskie",
    "Września": "Wielkopolskie",
    "Wschowa": "Lubuskie",
    "Zamość": "Lubelskie",
    "Żary": "Lubuskie",
    "Zbąszyń": "Wielkopolskie",
    "Zduńska Wola": "Łódzkie",
    "Zielona Góra": "Lubuskie",
    "Złocieniec": "Zachodniopomorskie"
}