miasta_wojewodztwa = {
    'Aleksandrów Łódzki': 'łódzkie',
    'Bełżyce': 'lubelskie',
    'Białogard': 'zachodniopomorskie',
    'Bielawa': 'dolnośląskie',
    'Bielsko-Biała': 'śląskie',
    'Błonie': 'mazowieckie',
    'Bochnia': 'małopolskie',
    'Bolesławiec': 'dolnośląskie',
    'Braniewo': 'warmińsko-mazurskie',
    'Brodnica': 'kujawsko-pomorskie',
    'Brzeg Dolny': 'dolnośląskie',
    'Brzeg': 'opolskie',
    'Brzesko': 'małopolskie',
    'Brzeszcze': 'małopolskie',
    'Brzeziny': 'łódzkie',
    'Bukowno': 'małopolskie',
    'Bystrzyca Kłodzka': 'dolnośląskie',
    'Bytom': 'śląskie',
    'Chodzież': 'wielkopolskie',
    'Chojna': 'zachodniopomorskie',
    'Choszczno': 'zachodniopomorskie',
    'Chybie': 'śląskie',
    'Ciechocinek': 'kujawsko-pomorskie',
    'Cieszyn': 'śląskie',
    'Czarnków': 'wielkopolskie',
    'Czerwionka-Leszczyny': 'śląskie',
    'Dąbrowa Górnicza': 'śląskie',
    'Darłowo': 'zachodniopomorskie',
    'Dęblin': 'mazowieckie',
    'Dębno': 'zachodniopomorskie',
    'Drawsko Pomorskie': 'zachodniopomorskie',
    'Drezdenko': 'lubuskie',
    'Działdowo': 'warmińsko-mazurskie',
    'Dzierżoniów': 'dolnośląskie',
    'Ełk': 'warmińsko-mazurskie',
    'Gdańsk': 'pomorskie',
    'Gdynia': 'pomorskie',
    'Giżycko': 'warmińsko-mazurskie',
    'Głogów': 'dolnośląskie',
    'Głubczyce': 'opolskie',
    'Głuchołazy': 'opolskie',
    'Gniezno': 'wielkopolskie',
    'Goleniów': 'zachodniopomorskie',
    'Golub-Dobrzyń': 'kujawsko-pomorskie',
    'Góra': 'dolnośląskie',
    'Gorzów Wielkopolski': 'lubuskie',
    'Gostyń': 'wielkopolskie',
    'Grajewo': 'mazowieckie',
    'Grodzisk Wielkopolski': 'wielkopolskie',
    'Grójec': 'mazowieckie',
    'Grudziądz': 'kujawsko-pomorskie',
    'Gryfice': 'zachodniopomorskie',
    'Gryfino': 'zachodniopomorskie',
    'Iława': 'warmińsko-mazurskie',
    'Jarocin': 'wielkopolskie',
    'Jawor': 'dolnośląskie',
    'Jelcz-Laskowice': 'dolnośląskie',
    'Jelcz': 'dolnośląskie',
    'Jelenia Góra': 'dolnośląskie',
    'Kamienna Góra': 'dolnośląskie',
    'Katowice': 'śląskie',
    'Kępno': 'wielkopolskie',
    'Kluczbork': 'opolskie',
    'Kolbuszowa': 'podkarpackie',
    'Kołobrzeg': 'zachodniopomorskie',
    'Konin': 'wielkopolskie',
    'Kostrzyn nad Odrą': 'lubuskie',
    'Krotoszyn': 'wielkopolskie',
    'Krynica-Zdrój': 'małopolskie',
    'Kwidzyn': 'pomorskie',
    'Lębork': 'pomorskie',
    'Legnica': 'dolnośląskie',
    'Leszno': 'wielkopolskie',
    'Libiąż': 'małopolskie',
    'Lipno': 'kujawsko-pomorskie',
    'Łowicz': 'łódzkie',
    'Lubań': 'dolnośląskie',
    'Luboń': 'wielkopolskie',
    'Lubsko': 'lubuskie',
    'Lwówek Śląski': 'dolnośląskie',
    'Malbork': 'pomorskie',
    'Miechów': 'małopolskie',
    'Międzychód': 'wielkopolskie',
    'Międzyrzecz': 'lubuskie',
    'Milicz': 'dolnośląskie',
    'Mława': 'mazowieckie',
    'Mogilno': 'kujawsko-pomorskie',
    'Myślibórz': 'zachodniopomorskie',
    'Namysłów': 'opolskie',
    'Nowa Ruda': 'dolnośląskie',
    'Nowa Sól': 'lubuskie',
    'Nowogard': 'zachodniopomorskie',
    'Nowy Tomyśl': 'wielkopolskie',
    'Oborniki Śląskie': 'dolnośląskie',
    'Oborniki': 'wielkopolskie',
    'Oława': 'dolnośląskie',
    'Oleśnica': 'dolnośląskie',
    'Olsztyn': 'warmińsko-mazurskie',
    'Opalenica': 'wielkopolskie',
    'Ostróda': 'warmińsko-mazurskie',
    'Ostrów Wielkopolski': 'wielkopolskie',
    'Ostrzeszów': 'wielkopolskie',
    'Ozorków': 'łódzkie',
    'Pabianice': 'łódzkie',
    'Pajęczno': 'łódzkie',
    'Piekary Śląskie': 'śląskie',
    'Piła': 'wielkopolskie',
    'Polanica-Zdrój': 'dolnośląskie',
    'Police': 'zachodniopomorskie',
    'Polkowice': 'dolnośląskie',
    'Poznań': 'wielkopolskie',
    'Przemków': 'dolnośląskie',
    'Przeworsk': 'podkarpackie',
    'Pszczyna': 'śląskie',
    'Puck': 'pomorskie',
    'Pułtusk': 'mazowieckie',
    'Radlin': 'śląskie',
    'Radomsko': 'łódzkie',
    'Radzymin': 'mazowieckie',
    'Rawa Mazowiecka': 'łódzkie',
    'Rawicz': 'wielkopolskie',
    'Ruda Śląska': 'śląskie',
    'Ryki': 'lubelskie',
    'Rzeszów': 'podkarpackie',
    'Sanok': 'podkarpackie',
    'Skierniewice': 'łódzkie',
    'Skwierzyna': 'lubuskie',
    'Sławno': 'zachodniopomorskie',
    'Słubice': 'lubuskie',
    'Słupca': 'wielkopolskie',
    'Śrem': 'wielkopolskie',
    'Środa Śląska': 'dolnośląskie',
    'Środa Wielkopolska': 'wielkopolskie',
    'Stalowa Wola': 'podkarpackie',
    'Stare Miasto': 'kujawsko-pomorskie',
    'Starogard Gdański': 'pomorskie',
    'Strzelce Krajeńskie': 'lubuskie',
    'Strzelce Opolskie': 'opolskie',
    'Sucha Beskidzka': 'małopolskie',
    'Sulechów': 'lubuskie',
    'Sulęcin': 'lubuskie',
    'Swarzędz': 'wielkopolskie',
    'Świdnica': 'dolnośląskie',
    'Świdwin': 'zachodniopomorskie',
    'Świebodzice': 'dolnośląskie',
    'Świebodzin': 'lubuskie',
    'Szczecin': 'zachodniopomorskie',
    'Szczecinek': 'zachodniopomorskie',
    'Szczytno': 'warmińsko-mazurskie',
    'Szprotawa': 'lubuskie',
    'Tczew': 'pomorskie',
    'Tomaszów Lubelski': 'lubelskie',
    'Toruń': 'kujawsko-pomorskie',
    'Trzebiatów': 'zachodniopomorskie',
    'Trzebinia': 'małopolskie',
    'Trzebnica': 'dolnośląskie',
    'Turek': 'wielkopolskie',
    'Wągrowiec': 'wielkopolskie',
    'Wałcz': 'zachodniopomorskie',
    'Wejherowo': 'pomorskie',
    'Wieliczka': 'małopolskie',
    'Wieluń': 'łódzkie',
    'Wieruszów': 'łódzkie',
    'Wołów': 'dolnośląskie',
    'Wolsztyn': 'wielkopolskie',
    'Września': 'wielkopolskie',
    'Wschowa': 'lubuskie',
    'Zamość': 'lubelskie',
    'Żary': 'lubuskie',
    'Zbąszyń': 'wielkopolskie',
    'Zduńska Wola': 'łódzkie',
    'Zielona Góra': 'lubuskie',
    'Złocieniec': 'zachodniopomorskie'
}